# Pair Programming NumPy II

Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.

-Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:


In [1]:
import numpy as np

In [2]:
array = np.random.randint(0,100, (2,5,3))
array

array([[[35, 80, 91],
        [66, 14, 95],
        [26,  6, 69],
        [52, 87, 38],
        [47, 77, 82]],

       [[82, 54, 49],
        [45, 11, 81],
        [64, 67, 16],
        [91, 28, 66],
        [76, 28,  5]]])


- El valor de la primera fila y la segunda columna.

- Los valores de la segunda fila y las dos primeras columnas.

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

- Extraed los valores que sean mayores que 0.5.

- Extraed los valores menores que 0.2 o mayores que 0.5


In [3]:
array[0,0,1]

80

In [4]:
array[0,1,:2]

array([66, 14])

In [5]:
array[0,::2,:]

array([[35, 80, 91],
       [26,  6, 69],
       [47, 77, 82]])

In [6]:
array[array > 30]

# hemos puesto otro valor porque estamos trabajando con int

array([35, 80, 91, 66, 95, 69, 52, 87, 38, 47, 77, 82, 82, 54, 49, 45, 81,
       64, 67, 91, 66, 76])

In [7]:
array[(array > 30) | (array < 70)]

array([35, 80, 91, 66, 14, 95, 26,  6, 69, 52, 87, 38, 47, 77, 82, 82, 54,
       49, 45, 11, 81, 64, 67, 16, 91, 28, 66, 76, 28,  5])


Cread dos array de tres dimensiones:

- El primero de 2 matrices, 5 filas y 3 columnas.

- El segundo de 3 matrices, 2 filas y 5 columnas

In [8]:
array2 = np.random.randint(0,50, (2,5,3))
array3 = np.random.randint(0,50, (3,2,5))

In [9]:
array2

array([[[16, 36, 47],
        [15, 40, 20],
        [16,  9, 13],
        [30, 43, 48],
        [41, 27, 43]],

       [[ 3, 16,  3],
        [31, 19, 36],
        [23, 24, 11],
        [46, 48, 49],
        [17, 28, 13]]])

In [10]:
array3

array([[[37,  6, 28, 26, 25],
        [ 3,  5, 18, 14,  8]],

       [[11, 42, 43,  4, 39],
        [ 1, 36, 18, 15, 27]],

       [[32,  2, 48, 16, 44],
        [ 9, 21, 29, 33, 34]]])


- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [11]:
def propiedades (array):
    
    forma_array = array.shape
    tam_array = array.size
    dim_array = array.ndim
    tipo_array = array.dtype
    
    return f'La forma del array es {forma_array}, el tamaño del array es {tam_array}, las dimensiones del array son {dim_array}, el tipo del array es {tipo_array}'

In [12]:
propiedades(array2)

'La forma del array es (2, 5, 3), el tamaño del array es 30, las dimensiones del array son 3, el tipo del array es int64'

In [13]:
propiedades(array3)

'La forma del array es (3, 2, 5), el tamaño del array es 30, las dimensiones del array son 3, el tipo del array es int64'


- Sumad los dos arrays. ¿Podéis? ¿Por qué?


No podemos sumarlos poque tienen diferente forma.


Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:

- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [14]:
# utilizamos el reshape, cambiamos el array3 a la forma del array2 que es (2,5,3)
array_nuevo_3 = np.reshape(array, (2,5,3))
array_nuevo_3

array([[[35, 80, 91],
        [66, 14, 95],
        [26,  6, 69],
        [52, 87, 38],
        [47, 77, 82]],

       [[82, 54, 49],
        [45, 11, 81],
        [64, 67, 16],
        [91, 28, 66],
        [76, 28,  5]]])

In [15]:
suma1 = array2 + array_nuevo_3
suma1

array([[[ 51, 116, 138],
        [ 81,  54, 115],
        [ 42,  15,  82],
        [ 82, 130,  86],
        [ 88, 104, 125]],

       [[ 85,  70,  52],
        [ 76,  30, 117],
        [ 87,  91,  27],
        [137,  76, 115],
        [ 93,  56,  18]]])

In [16]:
# en este caso cambiamos mediante los indices la forma del array2 para que sea igual a la del array3 (3,2,5)
array_nuevo_2 = np.transpose(array2, (2,0,1))
array_nuevo_2

array([[[16, 15, 16, 30, 41],
        [ 3, 31, 23, 46, 17]],

       [[36, 40,  9, 43, 27],
        [16, 19, 24, 48, 28]],

       [[47, 20, 13, 48, 43],
        [ 3, 36, 11, 49, 13]]])

In [17]:
suma2 = array3 + array_nuevo_2
suma2

array([[[53, 21, 44, 56, 66],
        [ 6, 36, 41, 60, 25]],

       [[47, 82, 52, 47, 66],
        [17, 55, 42, 63, 55]],

       [[79, 22, 61, 64, 87],
        [12, 57, 40, 82, 47]]])

In [19]:

division = array3/array_nuevo_2

division

array([[[2.3125    , 0.4       , 1.75      , 0.86666667, 0.6097561 ],
        [1.        , 0.16129032, 0.7826087 , 0.30434783, 0.47058824]],

       [[0.30555556, 1.05      , 4.77777778, 0.09302326, 1.44444444],
        [0.0625    , 1.89473684, 0.75      , 0.3125    , 0.96428571]],

       [[0.68085106, 0.1       , 3.69230769, 0.33333333, 1.02325581],
        [3.        , 0.58333333, 2.63636364, 0.67346939, 2.61538462]]])

In [21]:
multiplicacion = array3 * array_nuevo_2

multiplicacion

array([[[ 592,   90,  448,  780, 1025],
        [   9,  155,  414,  644,  136]],

       [[ 396, 1680,  387,  172, 1053],
        [  16,  684,  432,  720,  756]],

       [[1504,   40,  624,  768, 1892],
        [  27,  756,  319, 1617,  442]]])

In [23]:
subtracion = array3 - array_nuevo_2

subtracion

array([[[ 21,  -9,  12,  -4, -16],
        [  0, -26,  -5, -32,  -9]],

       [[-25,   2,  34, -39,  12],
        [-15,  17,  -6, -33,  -1]],

       [[-15, -18,  35, -32,   1],
        [  6, -15,  18, -16,  21]]])