In [1]:
import numpy as np

Empezamos nuevo bloque de ejercicios de pair programming de NumPy.

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.



- Cread tres arrays: de una, dos y tres dimensiones. Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

1. El array de 2 dimensiones debe ser de 2 filas y 3 columnas
2. El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas
3. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.
4. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas
5. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.




In [12]:
lista1 = [2,5,7,11, 13]
lista2 = [[93,46,29, 54], [29,45,66,39]]
lista3 = [[[1,2,3],[4,5,6],[7,8,9]]]

array1 = np.array(lista1)


array1

array([ 2,  5,  7, 11, 13])

In [13]:
array2 = np.array(lista2)

array2

array([[93, 46, 29, 54],
       [29, 45, 66, 39]])

In [15]:
array3 = np.array(lista3)

array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [38]:
def propiedades (array):
    
    forma_array = array.shape
    tam_array = array.size
    dim_array = array.ndim
    tipo_array = array.dtype
    
    return f'La forma del array es {forma_array}, el tamaño del array es {tam_array}, las dimensiones del array son {dim_array}, el tipo del array es {tipo_array}'



In [39]:
propiedades(array3)

'La forma del array es (1, 3, 3), el tamaño del array es 9, las dimensiones del array son 3, el tipo del array es int64'

In [40]:
propiedades(array1)

'La forma del array es (5,), el tamaño del array es 5, las dimensiones del array son 1, el tipo del array es int64'

In [41]:
propiedades(array2)

'La forma del array es (2, 4), el tamaño del array es 8, las dimensiones del array son 2, el tipo del array es int64'

In [27]:
array4 = np.random.rand(2, 3, 3)

array4

array([[[0.53873044, 0.445512  , 0.62899803],
        [0.72300636, 0.56310088, 0.51427583],
        [0.06591832, 0.06687453, 0.36709861]],

       [[0.50314719, 0.07613235, 0.03718239],
        [0.56357926, 0.07244792, 0.4441579 ],
        [0.34788031, 0.5408287 , 0.85717654]]])

In [31]:
array_mat = np.eye(2, 3, 3)

array_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [33]:
array_mat2 = np.ones_like(array3)

array_mat2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

- Es el momento de hacer algunas operaciones entre arrays
1. ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
2. En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
3. Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
4. Dividid las dos matricess

In [35]:
suma_mat = array2 + array_mat2

# no se puede sumarlos porque no tienen la misma forma 

ValueError: operands could not be broadcast together with shapes (2,4) (1,3,3) 

In [36]:
print(array2)

[[93 46 29 54]
 [29 45 66 39]]


In [37]:
print(array_mat2)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]]
