# Pair Programming NumPy IV

Manos a la obra con la última lección de NumPy. En este caso pondremos en práctica como generar arrays que sigan ciertas distribuciones, así como las operaciones de teoría de conjuntos básicas.

¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?


In [1]:
import numpy as np

In [12]:
np.random.seed(1)

array1 = np.random.random_sample((3,5))

array1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [8]:
np.random.seed(1)

array2 = np.random.random_sample((3,5))

array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])


Cread los siguientes arrays:

Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

Elementos comunes entre los dos arrays

Unión de los dos arrays


In [27]:
uniforme = np.round(np.random.uniform(0,10, size = (2, 3, 5)),0)
uniforme

array([[[ 2.,  9.,  3.,  8.,  7.],
        [ 9.,  6.,  8.,  3.,  3.],
        [ 9.,  4., 10.,  7.,  6.]],

       [[ 1.,  9.,  4.,  6.,  4.],
        [ 2.,  9.,  6.,  0.,  6.],
        [ 3.,  5.,  9.,  4.,  9.]]])

In [32]:
unicos1 = np.unique(uniforme)
unicos1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
binomial = np.random.binomial(10, 0.3, size = (2, 3, 5))
binomial

array([[[4, 3, 5, 4, 3],
        [1, 1, 1, 1, 1],
        [2, 4, 3, 0, 1]],

       [[6, 3, 2, 2, 4],
        [2, 3, 6, 4, 2],
        [3, 3, 4, 2, 0]]])

In [33]:
unicos2 = np.unique(binomial)
unicos2

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
one_direction = np.intersect1d(unicos1, unicos2)
one_direction

array([0., 1., 2., 3., 4., 5., 6.])

In [35]:
union_one_direction = np.union1d(unicos1, unicos2)
union_one_direction

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])



¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?



In [36]:
set_ub = np.setdiff1d(uniforme, binomial)
set_ub

array([ 7.,  8.,  9., 10.])

In [37]:
# qué
set_bu = np.setdiff1d(binomial, uniforme)
set_bu

array([], dtype=int64)

In [39]:
print(binomial)
print(uniforme)

[[[4 3 5 4 3]
  [1 1 1 1 1]
  [2 4 3 0 1]]

 [[6 3 2 2 4]
  [2 3 6 4 2]
  [3 3 4 2 0]]]
[[[ 2.  9.  3.  8.  7.]
  [ 9.  6.  8.  3.  3.]
  [ 9.  4. 10.  7.  6.]]

 [[ 1.  9.  4.  6.  4.]
  [ 2.  9.  6.  0.  6.]
  [ 3.  5.  9.  4.  9.]]]


Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [42]:
array3 = np.random.randint(1,100, (80))
array3

array([77, 39, 92, 70, 99, 34, 44, 27, 57, 70, 74, 53, 90, 28, 44,  2, 83,
       95, 97, 27, 85, 31, 65, 23, 99, 53,  4, 71, 13, 40, 84, 49, 62, 71,
       14, 37, 24, 23, 67, 93, 96, 54, 10, 42, 58, 89, 94, 77, 83, 12, 37,
       17, 31, 85, 58, 36, 42, 82,  3, 86, 94, 37, 47, 81, 28, 73, 29,  3,
       14, 42, 37, 41, 19, 98, 39, 64, 47, 90,  3, 99])

In [44]:
array4 = np.random.randint(1,100, (80))
array4

array([69,  4, 59, 13,  3, 77, 97, 97, 62, 16, 75, 13, 19, 31, 60,  6, 17,
       96, 97, 61, 44, 32, 45, 25, 63, 80, 22, 20, 78, 34,  5, 40, 68, 35,
       35, 43, 79, 83, 39, 49, 82,  6, 92,  9, 41, 70,  6,  8, 79, 38, 79,
       34, 28, 52, 78, 31, 44, 47, 10, 68,  4, 68, 55, 98, 64, 81, 29, 38,
       65, 38, 94, 19, 79, 71, 93, 53, 11, 33, 47, 64])

In [45]:
unique1 = np.unique(array3)
unique1

array([ 2,  3,  4, 10, 12, 13, 14, 17, 19, 23, 24, 27, 28, 29, 31, 34, 36,
       37, 39, 40, 41, 42, 44, 47, 49, 53, 54, 57, 58, 62, 64, 65, 67, 70,
       71, 73, 74, 77, 81, 82, 83, 84, 85, 86, 89, 90, 92, 93, 94, 95, 96,
       97, 98, 99])

In [46]:
unique2 = np.unique(array4)
unique2

array([ 3,  4,  5,  6,  8,  9, 10, 11, 13, 16, 17, 19, 20, 22, 25, 28, 29,
       31, 32, 33, 34, 35, 38, 39, 40, 41, 43, 44, 45, 47, 49, 52, 53, 55,
       59, 60, 61, 62, 63, 64, 65, 68, 69, 70, 71, 75, 77, 78, 79, 80, 81,
       82, 83, 92, 93, 94, 96, 97, 98])

In [47]:
elementos_u1_u2 = np.setdiff1d(unique1, unique2)
elementos_u1_u2

array([ 2, 12, 14, 23, 24, 27, 36, 37, 42, 54, 57, 58, 67, 73, 74, 84, 85,
       86, 89, 90, 95, 99])

In [48]:
elementos_u2_u1 = np.setdiff1d(unique2, unique1)
elementos_u2_u1

array([ 5,  6,  8,  9, 11, 16, 20, 22, 25, 32, 33, 35, 38, 43, 45, 52, 55,
       59, 60, 61, 63, 68, 69, 75, 78, 79, 80])

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

¿Cuál es la relación que existe entre todos estos arrays? 

💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [49]:
comunes = np.intersect1d(array3, array4)
comunes

array([ 3,  4, 10, 13, 17, 19, 28, 29, 31, 34, 39, 40, 41, 44, 47, 49, 53,
       62, 64, 65, 70, 71, 77, 81, 82, 83, 92, 93, 94, 96, 97, 98])

In [53]:
print(len(array1))
print(len(array2))
print(len(array3))
print(len(array4))
print(len(binomial))


3
3
80
80
2
