# Pair Programming NumPy II

Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.

-Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:


In [1]:
import numpy as np

In [2]:
array = np.random.randint(0,100, (2,5,3))
array

array([[[78, 27, 16],
        [64, 13, 53],
        [ 0, 31, 50],
        [10, 49, 54],
        [67, 66, 76]],

       [[41, 91, 86],
        [67, 44, 69],
        [86, 37, 90],
        [68, 45, 21],
        [96, 58, 75]]])


- El valor de la primera fila y la segunda columna.

- Los valores de la segunda fila y las dos primeras columnas.

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

- Extraed los valores que sean mayores que 0.5.

- Extraed los valores menores que 0.2 o mayores que 0.5


In [5]:
array[0,0,1]

27

In [8]:
array[0,1,:2]

array([64, 13])

In [9]:
array[0,::2,:]

array([[78, 27, 16],
       [ 0, 31, 50],
       [67, 66, 76]])

In [13]:
array[array > 30]

# hemos puesto otro valor porque estamos trabajando con int

array([78, 64, 53, 31, 50, 49, 54, 67, 66, 76, 41, 91, 86, 67, 44, 69, 86,
       37, 90, 68, 45, 96, 58, 75])

In [15]:
array[(array > 30) | (array < 70)]

array([78, 27, 16, 64, 13, 53,  0, 31, 50, 10, 49, 54, 67, 66, 76, 41, 91,
       86, 67, 44, 69, 86, 37, 90, 68, 45, 21, 96, 58, 75])


Cread dos array de tres dimensiones:

- El primero de 2 matrices, 5 filas y 3 columnas.

- El segundo de 3 matrices, 2 filas y 5 columnas

In [17]:
array2 = np.random.randint(0,50, (2,5,3))
array3 = np.random.randint(0,50, (3,2,5))

In [18]:
array2

array([[[ 3, 46, 29],
        [31, 26,  4],
        [31, 28, 16],
        [30, 15, 26],
        [ 1, 30, 36]],

       [[33, 26, 20],
        [26, 24, 33],
        [10, 43,  7],
        [30,  6, 28],
        [19, 32, 36]]])

In [19]:
array3

array([[[21,  0, 38, 28, 44],
        [33, 38, 35, 34,  1]],

       [[ 3, 10,  0, 20, 42],
        [39, 11, 28, 45, 19]],

       [[ 0, 21,  0, 39,  9],
        [42, 15, 31, 31, 40]]])


- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [20]:
def propiedades (array):
    
    forma_array = array.shape
    tam_array = array.size
    dim_array = array.ndim
    tipo_array = array.dtype
    
    return f'La forma del array es {forma_array}, el tamaño del array es {tam_array}, las dimensiones del array son {dim_array}, el tipo del array es {tipo_array}'

In [21]:
propiedades(array2)

'La forma del array es (2, 5, 3), el tamaño del array es 30, las dimensiones del array son 3, el tipo del array es int64'

In [22]:
propiedades(array3)

'La forma del array es (3, 2, 5), el tamaño del array es 30, las dimensiones del array son 3, el tipo del array es int64'


- Sumad los dos arrays. ¿Podéis? ¿Por qué?


No podemos sumarlos poque tienen diferente forma.


Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:

- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [25]:
# utilizamos el reshape, cambiamos el array3 a la forma del array2 que es (2,5,3)
array_nuevo_3 = np.reshape(array, (2,5,3))
array_nuevo_3

array([[[78, 27, 16],
        [64, 13, 53],
        [ 0, 31, 50],
        [10, 49, 54],
        [67, 66, 76]],

       [[41, 91, 86],
        [67, 44, 69],
        [86, 37, 90],
        [68, 45, 21],
        [96, 58, 75]]])

In [31]:
suma1 = array2 + array_nuevo_3
suma1

array([[[ 81,  73,  45],
        [ 95,  39,  57],
        [ 31,  59,  66],
        [ 40,  64,  80],
        [ 68,  96, 112]],

       [[ 74, 117, 106],
        [ 93,  68, 102],
        [ 96,  80,  97],
        [ 98,  51,  49],
        [115,  90, 111]]])

In [ ]:
# en este caso cambiamos mediante los indices la forma del array2 para que sea igual a la del array3 (3,2,5)
array_nuevo_2 = np.transpose(array2, (2,0,1))
array_nuevo_2

In [32]:
suma2 = array3 + array_nuevo_2
suma2

array([[[24, 31, 69, 58, 45],
        [66, 64, 45, 64, 20]],

       [[49, 36, 28, 35, 72],
        [65, 35, 71, 51, 51]],

       [[29, 25, 16, 65, 45],
        [62, 48, 38, 59, 76]]])

In [27]:
#(3,2,5)
array3

array([[[21,  0, 38, 28, 44],
        [33, 38, 35, 34,  1]],

       [[ 3, 10,  0, 20, 42],
        [39, 11, 28, 45, 19]],

       [[ 0, 21,  0, 39,  9],
        [42, 15, 31, 31, 40]]])