# Pair Programming NumPy I

Es el momento de hacer algunas operaciones entre arrays

- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
- Dividid las dos matricess

In [1]:
import numpy as np

Empezamos nuevo bloque de ejercicios de pair programming de NumPy.

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.



- Cread tres arrays: de una, dos y tres dimensiones. Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

    - El array de 2 dimensiones debe ser de 2 filas y 3 columnas
    - El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas
    - Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.
    - Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas
    - Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.




In [2]:
lista1 = [2,5,7,11, 13]
lista2 = [[93,46,29, 54], [29,45,66,39]]
lista3 = [[[1,2,3],[4,5,6],[7,8,9]]]

array1 = np.array(lista1)


array1

array([ 2,  5,  7, 11, 13])

In [3]:
array2 = np.array(lista2)

array2

array([[93, 46, 29, 54],
       [29, 45, 66, 39]])

In [4]:
array3 = np.array(lista3)

array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
def propiedades (array):
    
    forma_array = array.shape
    tam_array = array.size
    dim_array = array.ndim
    tipo_array = array.dtype
    
    return f'La forma del array es {forma_array}, el tamaño del array es {tam_array}, las dimensiones del array son {dim_array}, el tipo del array es {tipo_array}'



In [6]:
propiedades(array3)

'La forma del array es (1, 3, 3), el tamaño del array es 9, las dimensiones del array son 3, el tipo del array es int64'

In [7]:
propiedades(array1)

'La forma del array es (5,), el tamaño del array es 5, las dimensiones del array son 1, el tipo del array es int64'

In [8]:
propiedades(array2)

'La forma del array es (2, 4), el tamaño del array es 8, las dimensiones del array son 2, el tipo del array es int64'

In [9]:
array4 = np.random.rand(2, 3, 3)

array4

array([[[0.24301757, 0.09560101, 0.98500354],
        [0.25513276, 0.18191308, 0.3999162 ],
        [0.95403622, 0.67088497, 0.4686428 ]],

       [[0.19980698, 0.72403664, 0.06566355],
        [0.13376195, 0.5633426 , 0.79176046],
        [0.34827228, 0.28119178, 0.02347893]]])

In [10]:
array_mat = np.eye(2, 3, 3)

array_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
array_mat2 = np.ones_like(array3)

array_mat2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

- Es el momento de hacer algunas operaciones entre arrays

    - ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

    - En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

    - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
    
    - Dividid las dos matricess

In [ ]:
print(array2)

[[93 46 29 54]
 [29 45 66 39]]


In [ ]:
print(array_mat2)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# revisar
array2_nuevo = 