# Pair Programming NumPy III

# Operaciones estadísticas y matemáticas

En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. 
Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

- Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:
    - Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.
    - Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.
    - Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.
    - Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

A modo de ejemplo. Si tenemos el siguiente array


In [3]:
import numpy as np

In [7]:
# ([[[0.4, 0.7, 0.2, 0.9, 0.2],
#     [0.1, 0.9, 0.6, 0.1, 0.2],
#     [1. , 0.2, 0.1, 0.8, 0.3]],
# ​
#    [[0. , 0.3, 0.4, 0.5, 0.1],
#     [0.5, 0.7, 0.9, 0. , 0.8],
#     [0.5, 0.3, 0.5, 0.8, 0.1]]])

sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0
​
nuestro array vacío debería quedar como este: 


In [8]:
# ([[["A", "B", "C", "B", "C"],
#     ["C", "B", "B", "C", "C"],
#     ["D" , "C", "C", "B", "C"]],
# ​
#    [["E" , "C", "A", "B", "C"],
#     ["B", "B","B", "E" , "B"],
#     ["B", "C", "B", "B", "C"]]])

In [21]:
array1 = np.round(np.random.rand(2, 3, 5), 1)


array1

array([[[0.1, 0.4, 0.3, 0.3, 0.4],
        [0.8, 0.5, 0.6, 0.9, 0.2],
        [0.6, 0.3, 0.5, 0.3, 0.2]],

       [[0.9, 0.2, 0.6, 0.3, 0.8],
        [0.5, 0.4, 0.2, 0.5, 0.9],
        [0.9, 0.6, 0.3, 0.4, 1. ]]])

In [22]:
amedia = np.round(np.mean(array1), 1)

amedia

0.5

In [23]:
amax = np.max(array1)

amax

1.0

In [24]:
amin = np.min(array1)

amin

0.1

In [25]:
avacio = np.round(np.empty_like(array1),1)

avacio

array([[[0.1, 0.4, 0.3, 0.3, 0.4],
        [0.8, 0.5, 0.6, 0.9, 0.2],
        [0.6, 0.3, 0.5, 0.3, 0.2]],

       [[0.9, 0.2, 0.6, 0.3, 0.8],
        [0.5, 0.4, 0.2, 0.5, 0.9],
        [0.9, 0.6, 0.3, 0.4, 1. ]]])

In [26]:
array_nuevo = np.empty((2,3,5), dtype = str)

for i in range(array1.shape[0]):
    for j in range(array1.shape[1]):
        for k in range(array1.shape[2]):
            
            if array1[i,j,k]  == amedia:
                array_nuevo[i,j,k] = "A"
            elif array1[i,j,k] >  amedia:
                array_nuevo[i,j,k] = "B"
            elif array1[i,j,k] <  amedia:
                array_nuevo[i,j,k] = "C"
            elif array1[i,j,k] == amax:
                array_nuevo[i,j,k] = "D"
            elif array1[i,j,k] == amin:
                array_nuevo[i,j,k] = "E"
    
print(array_nuevo)

[[['C' 'C' 'C' 'C' 'C']
  ['B' 'A' 'B' 'B' 'C']
  ['B' 'C' 'A' 'C' 'C']]

 [['B' 'C' 'B' 'C' 'B']
  ['A' 'C' 'C' 'A' 'B']
  ['B' 'B' 'C' 'C' 'B']]]



💡 Pista 💡 

Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

En este caso:

-  Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
-  Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
-  Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
- Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [20]:
avacio1 = np.empty(30, dtype=int)

avacio1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# ambos los arrays tienen 30 elementos, así que podemos crear un contador para acceder al array unidimensional de manera sequencial y  ordenada 

contador = 0
for matriz in array_nuevo:
  for fila in matriz:
    for ele in fila:
      if ele == "A" or ele == "B":
        avacio1[contador] = 1
      elif ele == "C" or ele == "D":
        avacio1[contador] = 2
      else:
        avacio1[contador] = 3
      contador += 1

In [32]:
avacio1

array([2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2,
       2, 1, 1, 1, 1, 2, 2, 1])

In [34]:
avacio1.reshape(2, 3, 5)

array([[[2, 2, 2, 2, 2],
        [1, 1, 1, 1, 2],
        [1, 2, 1, 2, 2]],

       [[1, 2, 1, 2, 1],
        [1, 2, 2, 1, 1],
        [1, 1, 2, 2, 1]]])